### ISSUE TITLE
discrepencies in manual / automated setup script re: where oc, argocd etc... come from

### ISSUE THREAD

**Issue by zilkey** [upslopeio/ibm-cloud-garage-training#18]
Automated script has them come from brew

Manual script has them come from shell.cloudnativetoolkit.dev

**Comment by dalelotts** [comment]
Does this cause a problem?

**Comment by dalelotts** [comment]
It turns out the manual steps can cause a "exec format error" when running tkn - the solution is to `rm ~/bin/tkn` and then run `brew install tekton-cli`

**Comment by dalelotts** [comment]
No longer an issue and AME setup is entirely manual
